# Generated by Django 6.1.1 on 2026-09-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=100)),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Evening', 'Evening')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('relation', models.CharField(choices=[('Parent', 'Parent'), ('Spouse', 'Spouse'), ('Sibling', 'Sibling'), ('Child', 'Child'), ('Relative', 'Relative'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20)),
                ('visitor_number', models.PositiveSmallIntegerField()),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visit_time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
    ]
