# Generated by Django 6.1.1 on 2026-10-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_check_out_visit_duration_minutes_visit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
