# Generated by Django 6.1.1 on 2026-09-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('PATIENTS', 'Patients'), ('VISITOR_CHECK', 'Visitor Check'), ('REPORTS', 'Reports'), ('USER_UPLOAD', 'User Upload'), ('USER_MANAGEMENT', 'User Management'), ('SYSTEM_SETTINGS', 'System Settings')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='module_permissions',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.modulepermission'),
        ),
    ]
