
"""
Django settings for followup_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path
from datetime import timedelta
from urllib.parse import urlparse

from decouple import config, Csv


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

# SECRET_KEY is read from environment variables
SECRET_KEY = config('SECRET_KEY')


# Local:
# DEBUG=True
#
# Render:
# DEBUG=False
DEBUG = config(
    'DEBUG',
    default=True,
    cast=bool
)


# =========================================================
# ALLOWED HOSTS
# =========================================================

# Local .env:
# ALLOWED_HOSTS=127.0.0.1,localhost
#
# Render environment variable:
# ALLOWED_HOSTS=followup-system-backend.onrender.com,localhost,127.0.0.1

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost,.onrender.com',
    cast=Csv()
)


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # -----------------------------------------------------
    # Django
    # -----------------------------------------------------

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # -----------------------------------------------------
    # CORS
    # -----------------------------------------------------

    'corsheaders',


    # -----------------------------------------------------
    # Django REST Framework
    # -----------------------------------------------------

    'rest_framework',
    'rest_framework_simplejwt',


    # -----------------------------------------------------
    # Project Apps
    # -----------------------------------------------------

    'accounts',
    'patients',
    'visits',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    # CORS must be placed before CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise for production static files
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# CORS
# =========================================================

# ---------------------------------------------------------
# Local frontend
# ---------------------------------------------------------

LOCAL_FRONTEND_URL = 'http://localhost:4200'
LOCAL_FRONTEND_IP = 'http://127.0.0.1:4200'


# ---------------------------------------------------------
# Production frontend
# ---------------------------------------------------------

PRODUCTION_FRONTEND_URL = (
    'https://followup-system-el98.onrender.com'
)


# ---------------------------------------------------------
# CORS allowed origins
#
# We also allow configuration through Render environment
# variables.
#
# Render:
# CORS_ALLOWED_ORIGINS=https://followup-system-el98.onrender.com
#
# Local:
# CORS_ALLOWED_ORIGINS=http://localhost:4200,http://127.0.0.1:4200
# ---------------------------------------------------------

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default=(
        'http://localhost:4200,'
        'http://127.0.0.1:4200,'
        'https://followup-system-el98.onrender.com'
    ),
    cast=Csv()
)


# =========================================================
# CSRF TRUSTED ORIGINS
# =========================================================

# This is separate from CORS.
#
# It allows the production frontend to make trusted
# unsafe requests when Django's CSRF protection applies.

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default=(
        'http://localhost:4200,'
        'http://127.0.0.1:4200,'
        'https://followup-system-el98.onrender.com'
    ),
    cast=Csv()
)


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'followup_backend.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'followup_backend.wsgi.application'


# =========================================================
# DATABASE
#
# If DATABASE_URL exists:
#     Use Render PostgreSQL
#
# If DATABASE_URL does not exist:
#     Use local PostgreSQL
# =========================================================

DATABASE_URL = config(
    'DATABASE_URL',
    default=''
)


if DATABASE_URL:

    # -----------------------------------------------------
    # Render PostgreSQL
    # -----------------------------------------------------

    db_url = urlparse(DATABASE_URL)

    DATABASES = {

        'default': {

            'ENGINE':
                'django.db.backends.postgresql',

            'NAME':
                db_url.path.lstrip('/'),

            'USER':
                db_url.username,

            'PASSWORD':
                db_url.password,

            'HOST':
                db_url.hostname,

            'PORT':
                db_url.port or 5432,

            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }


else:

    # -----------------------------------------------------
    # Local PostgreSQL
    # -----------------------------------------------------

    DATABASES = {

        'default': {

            'ENGINE':
                'django.db.backends.postgresql',

            'NAME':
                config('DB_NAME'),

            'USER':
                config('DB_USER'),

            'PASSWORD':
                config('DB_PASSWORD'),

            'HOST':
                config(
                    'DB_HOST',
                    default='localhost'
                ),

            'PORT':
                config(
                    'DB_PORT',
                    default='5432'
                ),
        }
    }


# =========================================================
# CUSTOM USER MODEL
# =========================================================

AUTH_USER_MODEL = 'accounts.User'


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# =========================================================
# WHITENOISE
# =========================================================

STORAGES = {

    'default': {

        'BACKEND':
            'django.core.files.storage.FileSystemStorage',
    },

    'staticfiles': {

        'BACKEND':
            'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)


# =========================================================
# DJANGO REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {

    # -----------------------------------------------------
    # JWT Authentication
    # -----------------------------------------------------

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ),


    # -----------------------------------------------------
    # Authentication required by default
    # -----------------------------------------------------

    'DEFAULT_PERMISSION_CLASSES': (

        'rest_framework.permissions.IsAuthenticated',

    ),
}


# =========================================================
# SIMPLE JWT
# =========================================================

SIMPLE_JWT = {

    # -----------------------------------------------------
    # Access token validity
    # -----------------------------------------------------

    'ACCESS_TOKEN_LIFETIME':
        timedelta(
            minutes=30
        ),


    # -----------------------------------------------------
    # Refresh token validity
    # -----------------------------------------------------

    'REFRESH_TOKEN_LIFETIME':
        timedelta(
            days=1
        ),


    # -----------------------------------------------------
    # Authentication header
    # -----------------------------------------------------

    'AUTH_HEADER_TYPES': (
        'Bearer',
    ),


    # -----------------------------------------------------
    # Update last_login after successful login
    # -----------------------------------------------------

    'UPDATE_LAST_LOGIN': True,
}


# =========================================================
# PRODUCTION SECURITY
# =========================================================

# Render terminates HTTPS before forwarding requests
# to the Django application.

SECURE_PROXY_SSL_HEADER = (
    'HTTP_X_FORWARDED_PROTO',
    'https'
)