"""
Django settings for followup_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# SECURITY
# =========================================================

# Keep your existing SECRET_KEY value locally.
# Do not commit it to GitHub.
SECRET_KEY = 'YOUR_EXISTING_DJANGO_SECRET_KEY'

DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # CORS
    'corsheaders',

    # Django REST Framework
    'rest_framework',
    'rest_framework_simplejwt',

    # Project apps
    'accounts',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    # IMPORTANT:
    # Must be placed before CommonMiddleware.
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# CORS
# Angular development server
# =========================================================

CORS_ALLOWED_ORIGINS = [

    'http://localhost:4200',

    'http://127.0.0.1:4200',
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'followup_backend.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'followup_backend.wsgi.application'


# =========================================================
# DATABASE
# PostgreSQL
# =========================================================

DATABASES = {

    'default': {

        'ENGINE':
            'django.db.backends.postgresql',

        'NAME':
            'followup_system',

        'USER':
            'postgres',

        # IMPORTANT:
        # Put your existing PostgreSQL password here locally.
        # Do NOT commit this password to GitHub.
        'PASSWORD':
            'mohammed 1625',

        'HOST':
            'localhost',

        'PORT':
            '5432',
    }
}


# =========================================================
# CUSTOM USER MODEL
# =========================================================

AUTH_USER_MODEL = 'accounts.User'


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = 'static/'


# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)


# =========================================================
# DJANGO REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {

    # -----------------------------------------------------
    # JWT authentication
    # -----------------------------------------------------

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',

    ),

    # -----------------------------------------------------
    # All APIs require authentication by default
    # -----------------------------------------------------

    'DEFAULT_PERMISSION_CLASSES': (

        'rest_framework.permissions.IsAuthenticated',

    ),
}


# =========================================================
# SIMPLE JWT
# =========================================================

SIMPLE_JWT = {

    # -----------------------------------------------------
    # Access token validity
    # -----------------------------------------------------

    'ACCESS_TOKEN_LIFETIME':
        timedelta(
            minutes=30
        ),

    # -----------------------------------------------------
    # Refresh token validity
    # -----------------------------------------------------

    'REFRESH_TOKEN_LIFETIME':
        timedelta(
            days=1
        ),

    # -----------------------------------------------------
    # Authentication header
    # -----------------------------------------------------

    'AUTH_HEADER_TYPES': (
        'Bearer',
    ),

    # -----------------------------------------------------
    # Update Django last_login when login succeeds
    # -----------------------------------------------------

    'UPDATE_LAST_LOGIN': True,
}